"""Fixtures: a throwaway AzerothCore-shaped tree and an app pointed at it.

Nothing here touches a real install, database or worldserver. The auth DB is
a monkeypatched mysql_query serving canned rows whose SRP6 verifier was
generated by our own srp6.calculate_verifier — so a byte-order regression in
srp6.py fails the login tests, not just the unit vectors.
"""

import sys
from pathlib import Path

import pytest

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from testdeck import auth as tdauth             # noqa: E402
from testdeck import config as tdconfig        # noqa: E402
from testdeck import mysql as tdmysql          # noqa: E402
from testdeck import srp6                       # noqa: E402
from testdeck.app import create_app             # noqa: E402

APP_DIR = Path(__file__).resolve().parent.parent

WORLDSERVER_CONF = '''
LoginDatabaseInfo     = "127.0.0.1;3306;acore;pw;acore_auth"
WorldDatabaseInfo     = "127.0.0.1;3306;acore;pw;acore_world"
CharacterDatabaseInfo = "127.0.0.1;3306;acore;pw;acore_characters"
AccountInstancesPerHour = 7
'''

PLAYERBOTS_CONF = 'AiPlayerbot.RandomBotAccountPrefix = "testbot"\n'

DUNGEONCLEAR_CONF = 'DungeonClear.TestRun.DriverCharacter = "Dcdriver"\n'

# The test GM account served by the fake auth DB.
TEST_USER = "Tester"
TEST_PASSWORD = "secret-pw"
TEST_SALT = bytes(range(32))
TEST_VERIFIER = srp6.calculate_verifier(TEST_USER, TEST_PASSWORD, TEST_SALT)
TEST_ACCOUNT_ID = 42

# A valid five-name roster, shared by the route and authorization suites.
MEMBERS_DEFAULT = ["Tanky", "Healy", "Dpsa", "Dpsb", "Dpsc"]

# A second account with no GM level.
PLEB_USER = "Pleb"
PLEB_SALT = bytes(range(1, 33))
PLEB_VERIFIER = srp6.calculate_verifier(PLEB_USER, TEST_PASSWORD, PLEB_SALT)


@pytest.fixture
def tree(tmp_path):
    """A minimal server layout: etc/ with both confs, bin/ for logs+sidecars,
    and a fake built dist/ for the SPA."""
    dist = tmp_path / "env" / "dist"
    (dist / "etc" / "modules").mkdir(parents=True)
    (dist / "bin").mkdir(parents=True)
    (dist / "etc" / "worldserver.conf").write_text(WORLDSERVER_CONF)
    (dist / "etc" / "modules" / "playerbots.conf").write_text(PLAYERBOTS_CONF)
    (dist / "etc" / "modules" / "mod_dungeon_clear.conf").write_text(
        DUNGEONCLEAR_CONF)
    (dist / "bin" / "Server.log").write_text("line one\nline two\n")
    web = tmp_path / "app" / "dist"
    (web / "assets").mkdir(parents=True)
    (web / "index.html").write_text("<!doctype html><title>DC Test Deck</title>")
    return tmp_path


@pytest.fixture
def cfg(tree, tmp_path):
    toml = tree / "testdeck.toml"
    toml.write_text(f'''
[paths]
base = "{tree}"
data_dir = "{tmp_path / 'data'}"

[server]
port = 8999

[auth]
min_gmlevel = 1
admin_gmlevel = 3
session_hours = 1

[bridge]
type = "screen"
screen_session = "testworld"

[realm]
status_check = "none"
''')
    tdmysql.reset_creds_cache()
    c = tdconfig.load(str(toml), app_dir=tree / "app")
    # No privilege probe: the suite must pass on a machine with no sudo rules.
    tdconfig.validate(c, check_privileges=False)
    return c


def fake_auth_db(monkeypatch, gmlevel=3, accounts=None):
    """Monkeypatch mysql_query to serve the canned auth tables. Character-side
    queries return [] unless a test overrides further."""
    accounts = accounts if accounts is not None else {
        TEST_USER: (TEST_ACCOUNT_ID, TEST_SALT, TEST_VERIFIER),
        PLEB_USER: (77, PLEB_SALT, PLEB_VERIFIER),
    }
    gm = {TEST_ACCOUNT_ID: gmlevel}

    async def fake_query(which, sql):
        if which == "auth" and "FROM account " in sql:
            for name, (aid, salt, verifier) in accounts.items():
                if f"username = '{name}'" in sql:
                    return [[str(aid), salt.hex().upper(), verifier.hex().upper()]]
            return []
        if which == "auth" and "account_access" in sql:
            for aid, lvl in gm.items():
                if f"id = {aid} " in sql:
                    return [[str(lvl)]]
            return [["0"]]
        return []

    monkeypatch.setattr(tdauth, "mysql_query", fake_query)
    return fake_query


def make_client(cfg, host="127.0.0.1"):
    """TestClient defaults its client host to the string "testclient", which
    restrict_to_lan rejects outright (it is not an IP) — so every request
    would 403 for the wrong reason. Give it a real address.

    Its default base_url is http://testserver, and the Host check rejects
    unlisted NAMES, so that has to be an address too."""
    from fastapi.testclient import TestClient
    return TestClient(create_app(cfg, start_collectors=False),
                      client=(host, 51000), base_url="http://127.0.0.1:8999")


@pytest.fixture
def client(cfg, monkeypatch):
    """A logged-in GM client with the CSRF header set — what every test that
    is about a route rather than about auth wants. The auth suite builds its
    own clients with make_client() so it can exercise the unauthenticated
    paths."""
    fake_auth_db(monkeypatch)
    with make_client(cfg) as c:
        c.headers["X-TestDeck"] = "1"
        r = c.post("/api/login", json={"username": TEST_USER,
                                       "password": TEST_PASSWORD})
        assert r.status_code == 200, r.text
        yield c
