"""GM-account login: the whole gate, with the auth DB faked at mysql_query.

The canned rows' verifiers are generated by srp6.calculate_verifier itself,
so these tests exercise the real SRP6 path end to end.
"""

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from conftest import (PLEB_USER, TEST_PASSWORD, TEST_USER,  # noqa: E402
                      fake_auth_db, make_client)


def login(c, username=TEST_USER, password=TEST_PASSWORD):
    return c.post("/api/login", json={"username": username, "password": password})


def test_login_ok_sets_session(cfg, monkeypatch):
    fake_auth_db(monkeypatch)
    with make_client(cfg) as c:
        r = login(c)
        assert r.status_code == 200
        body = r.json()
        assert body["username"] == TEST_USER
        assert body["gmlevel"] == 3
        assert body["admin"] is True
        s = c.get("/api/session").json()
        assert s["authenticated"] is True
        assert s["username"] == TEST_USER


def test_wrong_password_and_unknown_user_are_the_same_401(cfg, monkeypatch):
    """No account-name oracle: both failures answer identically."""
    fake_auth_db(monkeypatch)
    with make_client(cfg) as c:
        r1 = login(c, password="nope")
        r2 = login(c, username="Nobody", password="nope")
        assert r1.status_code == r2.status_code == 401
        assert r1.json() == r2.json()


def test_gmlevel_zero_is_403_with_reason(cfg, monkeypatch):
    """The tester's password was right — tell them what to fix."""
    fake_auth_db(monkeypatch)
    with make_client(cfg) as c:
        r = login(c, username=PLEB_USER)
        assert r.status_code == 403
        assert "GM level" in r.json()["detail"]


def test_min_gmlevel_respected(cfg, monkeypatch):
    cfg.min_gmlevel = 4
    fake_auth_db(monkeypatch, gmlevel=3)
    with make_client(cfg) as c:
        assert login(c).status_code == 403


def test_api_requires_session(cfg):
    with make_client(cfg) as c:
        assert c.get("/api/testruns").status_code == 401


def test_spa_shell_is_public(cfg):
    with make_client(cfg) as c:
        assert c.get("/").status_code == 200
        assert c.get("/live").status_code == 200        # SPA fallback


def test_csrf_header_required(client):
    del client.headers["X-TestDeck"]
    r = client.post("/api/testruns/stop", json={"runId": "all"})
    assert r.status_code == 403
    assert "x-testdeck" in r.json()["detail"]


def test_cookie_tamper_is_rejected(cfg, monkeypatch):
    fake_auth_db(monkeypatch)
    with make_client(cfg) as c:
        login(c)
        cookie = c.cookies.get("tdeck")
    # Flip the embedded gmlevel; the HMAC must catch it. A fresh client so the
    # tampered cookie is the ONLY tdeck cookie in the jar.
    parts = cookie.split(".")
    parts[1] = "9"
    with make_client(cfg) as c2:
        c2.cookies.set("tdeck", ".".join(parts))
        assert c2.get("/api/testruns").status_code == 401


def test_throttle_per_ip_and_username(cfg, monkeypatch):
    """One app instance (one throttle), two source addresses: exhausting the
    limit from one IP must also lock the username for the other."""
    from fastapi.testclient import TestClient

    from testdeck.app import create_app

    fake_auth_db(monkeypatch)
    app = create_app(cfg, start_collectors=False)
    base = "http://127.0.0.1:8999"
    with TestClient(app, client=("127.0.0.1", 51000), base_url=base) as c:
        for _ in range(cfg.login_max_attempts):
            assert login(c, password="wrong").status_code == 401
        assert login(c).status_code == 429              # even the right password
    with TestClient(app, client=("127.0.0.2", 51001), base_url=base) as c2:
        assert login(c2).status_code == 429


def test_username_regex_blocks_sql(cfg, monkeypatch):
    """The username is the one user-typed value that reaches SQL — anything
    outside the allowlist must die before the query."""
    seen = []

    async def spy(which, sql):
        seen.append(sql)
        return []

    import testdeck.auth as tdauth
    monkeypatch.setattr(tdauth, "mysql_query", spy)
    with make_client(cfg) as c:
        r = login(c, username="x'; DROP TABLE account; --")
        assert r.status_code == 401
        assert seen == []                               # never reached the DB


def test_admin_gate(cfg, monkeypatch):
    """gmlevel 1 can use the API but not clear shared history."""
    fake_auth_db(monkeypatch, gmlevel=1)
    with make_client(cfg) as c:
        c.headers["X-TestDeck"] = "1"
        assert login(c).status_code == 200
        r = c.post("/api/testruns/clear")
        assert r.status_code == 403
        assert "GM level 3" in r.json()["detail"]


def test_logout(client):
    assert client.post("/api/logout").status_code == 200
    assert client.get("/api/session").json()["authenticated"] is False


def test_missing_mysql_client_names_the_fix(cfg, monkeypatch):
    """The most common first-run failure must not reach a tester's browser as
    a bare errno. The login is refused as a SERVER problem (503, not 401), and
    the message says what to install and which key to set."""
    import testdeck.mysql as tdmysql

    async def no_binary(argv, **kw):
        raise FileNotFoundError(2, "No such file or directory", argv[0])

    monkeypatch.setattr(tdmysql, "spawn", no_binary)
    with make_client(cfg) as c:
        r = login(c)
        assert r.status_code == 503
        detail = r.json()["detail"]
        assert "MySQL client" in detail
        assert "mysql_bin" in detail
